### ISSUE TITLE
Recommended modules button is too long on legacy pages

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#91]
Recommended modules button on legacy pages is too long, almost 45 seconds before displaying something

**Comment by Matt75** [comment]
Did you try with new version ? https://github.com/PrestaShop/ps_mbo/pull/89

It should be more faster due to cache usage :
First call is always long due to *multiple API calls necessary* to build Recommended Modules because we still rely on legacy API. And we have to detected installed modules and modules already on disk, heavy process.

I made my best for new version, I think we can't do better until new API availability.
But I introduced CircuitBreaker for retrieve xml file contain recommended modules and add a cache after recommended modules building for increase response time.

This will be better when new API will be available, we should be able to retrieve only recommended modules for requested Tab in one API call.

**Comment by marionf** [comment]
I had not tried yet but you're right it's really better, thanks @Matt75
